# Generated by Django 2.2.16 on 2022-07-31 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Комментарии'},
        ),
    ]
